nelmio_cors:
    paths:
        "^/api":
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['Origin','Accept','Content-Type','Authorization']
            allow_methods: ['POST', 'GET']
