twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['forms/form_layout.html.twig']
    globals:
        admin_website_url: '%env(SENDIT_ADMIN_WEBSITE_URL)%'
        user_website_url: '%env(SENDIT_USER_WEBSITE_URL)%'
        marketing_website_url: '%env(SENDIT_MARKETING_WEBSITE_URL)%'

when@test:
    twig:
        strict_variables: true
